name: Generate-Dataset-File-Pipeline

on:
  push:
  pull_request:
    branches:
    - release
    - dev

  schedule:
    - cron: '*/1440 * * * *'

  workflow_dispatch:
  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
jobs:
  generate_dataset_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate .csv file
        run: |
          python script.py --username ${{secrets.USERNAME}} --password ${{secrets.PASSWORD}} --original_file_url ${{vars.FILE_URL}}
